#
#
#
attachment::att_amend_desc()
golem::add_module(name = "01-meta", with_test = FALSE)
golem::add_module(name = "02-app", with_test = FALSE)
golem::add_fct("helpers", with_test = TRUE)
golem::add_utils("helpers", with_test = TRUE)
golem::add_js_file("location")
golem::add_js_handler("handlers")
golem::add_css_file("custom")
golem::add_sass_file("custom")


usethis::use_package( "bslib" )
usethis::use_package( "dplyr" )
usethis::use_package( "lubridate" )
usethis::use_package( "shinycssloaders" )
usethis::use_package( "ggplot2" )
# usethis::use_package( "ggrepel" )
usethis::use_package( "glue" )
# usethis::use_package( "gt" )
usethis::use_package( "hrbrthemes" )
usethis::use_package( "htmltools" )
# usethis::use_package( "hunspell" )
# usethis::use_package( "ggtext" )
# usethis::use_package( "janitor" )
# usethis::use_package( "kableExtra" )
# usethis::use_package( "knitr" )
usethis::use_package( "leaflet" )
usethis::use_package( "leaflet.extras" )
# usethis::use_package( "magrittr" )
usethis::use_package( "metathis" )
usethis::use_package( "patchwork" )
usethis::use_package( "ragg" )
usethis::use_package( "readr" )
usethis::use_package( "sf" )
usethis::use_package( "shiny" )
usethis::use_package( "sparkline" )
usethis::use_package( "DT" )


# usethis::use_package( "shinycssloaders" )
# usethis::use_package( "spelling" )
# usethis::use_package( "stringr" )
# usethis::use_package( "svglite" )
# usethis::use_package( "tidyr" )
# usethis::use_package( "xtable" )

usethis::use_data_raw(name = "my_dataset", open = FALSE)
usethis::use_test("app")
usethis::use_vignette("tellinkiappi")
devtools::build_vignettes()
usethis::use_coverage()
covrpage::covrpage()
usethis::use_github()
usethis::use_github_action()
usethis::use_github_action_check_release()
usethis::use_github_action_check_standard()
usethis::use_github_action_check_full()
usethis::use_github_action_pr_commands()
usethis::use_travis()
usethis::use_travis_badge()
usethis::use_appveyor()
usethis::use_appveyor_badge()
usethis::use_circleci()
usethis::use_circleci_badge()
usethis::use_jenkins()
usethis::use_gitlab_ci()
rstudioapi::navigateToFile("dev/03_deploy.R")
